// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartHomeSystem.Context;

#nullable disable

namespace userdevice.Migrations
{
    [DbContext(typeof(UserDeviceContext))]
    partial class UserDeviceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartHomeSystem.Model.UserDevice", b =>
                {
                    b.Property<Int64?>("UserDeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<Int64?>("UserDeviceId"));

                    b.Property<Int64?>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UserId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.HasKey("UserDevicePrimary_Idx");

                    b.ToTable("UserDevice");
                    /*
                    b.HasData(
                        new
                        {
                            UserDeviceId = 2,
                            UserId = 1
                        },
                        new
                        {
                            UserDeviceId = 3,
                            UserId = 2
                        });
                    */
                });
#pragma warning restore 612, 618
        }
    }
}
